[unix_http_server]
file=/tmp/supervisor.sock
chmod=0770
chown=root:root

[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:app]
command=python3 -m app.main
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=120

[program:chromium]
command=chromium --display=:1 --window-size=1280,1080 --no-sandbox --disable-dev-shm-usage --disable-setuid-sandbox --disable-accelerated-2d-canvas --disable-gpu --disable-software-rasterizer --no-first-run --no-default-browser-check --user-data-dir=/root/.config/chromium \
    --remote-debugging-address=0.0.0.0 \
    --remote-debugging-port=8222 %(ENV_CHROME_ARGS)s
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DISPLAY=:1
priority=80
startretries=3
startsecs=2

[program:socat]
command=socat TCP-LISTEN:9222,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:8222
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=90
startsecs=2

[program:xvfb]
command=bash -c "rm -f /tmp/.X1-lock; Xvfb :1 -screen 0 1280x1080x24"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=70
startsecs=2

[program:x11vnc]
command=x11vnc -display :1 -forever -shared -nopw -listen 0.0.0.0 -xkb -rfbport 5900
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=100
startsecs=2

[program:websockify]
command=websockify 0.0.0.0:5901 localhost:5900
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=110
startsecs=2

; 使用分組統一啓動or關閉進程
[group:services]
programs=chromium,socat,xvfb,x11vnc,websockify,app