from app.domain.models.memory import Memory
from app.domain.models.file import File
from app.domain.models.event import BaseEvent
from app.domain.models.session import SessionStatus
from datetime import datetime
from typing import List
from typing import Optional
from typing import Protocol
from app.domain.models.session import Session


class SessionRepository(Protocol):
    async def save(self, session: Session) -> None: ...

    async def get_by_id(self, id: str) -> Optional[Session]: ...

    async def get_all(self) -> List[Session]: ...

    async def delete(self, id: str) -> None: ...

    async def update_title(self, id: str, title: str) -> None: ...

    async def update_latest_message(
        self, id: str, latest_message: str, timestamp: datetime
    ) -> None: ...

    async def update_unread_msg_count(
        self, id: str, unread_msg_count: int
    ) -> None: ...

    async def increment_unread_msg_count(self, id: str) -> None: ...

    async def decrement_unread_msg_count(self, id: str) -> None: ...

    async def update_status(self, id: str, status: SessionStatus) -> None: ...

    async def add_event(self, id: str, event: BaseEvent) -> None: ...

    async def add_file(self, id: str, file: File) -> None: ...

    async def get_file_by_path(self, id: str, path: str) -> Optional[File]: ...

    async def get_file_by_id(self, id: str, file_id: str) -> Optional[File]: ...

    async def save_memory(self, id: str, agent_name: str, memory: Memory) -> None: ...

    async def remove_file(self, id: str, file_id: str) -> None: ...

    async def remove_memory(self, id: str, agent_name: str) -> None: ...

    async def get_memory(self, id: str, agent_name: str) -> Optional[Memory]: ...

    async def update_created_at(self, id: str, created_at: datetime) -> None: ...

    async def update_updated_at(self, id: str, updated_at: datetime) -> None: ...
